## Broadcasting in Tensorflow

In [1]:
import tensorflow as tf

/Users/timlee/anaconda2/envs/py3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


### Addition

In [6]:
a = tf.constant(3, name='a')
b = tf.constant(5, name='b')
add_const = a + b

with tf.Session() as sess:
    print(sess.run(add_const))

8


In [7]:
a = tf.constant([1,2,3], name='a')
b = tf.constant(5, name='b')
const2tensor = a + b

with tf.Session() as sess:
    print(sess.run(const2tensor))

[6 7 8]


In [8]:
a = tf.constant([[1,2,3],[4,5,6]], name='a')
b = tf.constant([1,2,3], name='b')
tensor_add_tensor = a + b

with tf.Session() as sess:
    print(sess.run(tensor_add_tensor))

[[2 4 6]
 [5 7 9]]


### Multiplication

In [10]:
a = tf.constant(3, name='a')
b = tf.constant(5, name='b')
add_const = a * b

with tf.Session() as sess:
    print(sess.run(add_const))

15


In [33]:
a = tf.constant([1,2,3], name='a')
b = tf.constant(5, name='b')
const2tensor = tf.multiply(a, b)

with tf.Session() as sess:
    print(sess.run(const2tensor))

[ 5 10 15]


In [34]:
a = tf.constant([[1,2,3],[4,5,6]], name='a')
b = tf.constant([1,2,3], name='b')
tensor_add_tensor = tf.multiply(a, b)

with tf.Session() as sess:
    print(sess.run(tensor_add_tensor))

[[ 1  4  9]
 [ 4 10 18]]


### Most trouble happens with 1-D lists

In [35]:
m4 = tf.constant(55, name='alpha')
print(m4)
m5 = tf.constant([55], name='beta')
print(m5)
m6 = tf.constant([1,2], name='gamma')
print(m6)
m7 = tf.constant([[1],[2]], name='delta')
print(m7)
m8 = tf.constant([[1,2]], name='delta')
print(m8)

Tensor("alpha_2:0", shape=(), dtype=int32)
Tensor("beta_2:0", shape=(1,), dtype=int32)
Tensor("gamma_2:0", shape=(2,), dtype=int32)
Tensor("delta_3:0", shape=(2, 1), dtype=int32)
Tensor("delta_4:0", shape=(1, 2), dtype=int32)


In [39]:
m9 = tf.reshape(m6, shape=(-1,1))
print(m6)
with tf.Session() as sess:
    print(m6.eval())
    print(sess.run(m9))

Tensor("gamma_2:0", shape=(2,), dtype=int32)
[1 2]
[[1]
 [2]]
