## Constants, Sequences, Variables, Ops

In [1]:
import tensorflow as tf

/Users/timlee/anaconda2/envs/py3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [5]:
# note that we are reshaping the matrix
a = tf.constant(value=[[1,2,3,4,5],[10,20,30,40,50]],
                dtype=tf.float32,
                shape=[5,2],
                name="tf_const",
                verify_shape=False
               )
a_reshape = tf.reshape(a, shape=[2,5])

with tf.Session() as sess:
    result = sess.run([a, a_reshape])
    print(result[0])
    print(result[1])

[[ 1.  2.]
 [ 3.  4.]
 [ 5. 10.]
 [20. 30.]
 [40. 50.]]
[[ 1.  2.  3.  4.  5.]
 [10. 20. 30. 40. 50.]]


#### Making Empty Tensors

In [15]:
b = tf.zeros_like(a)

with tf.Session() as sess:
    print(sess.run(b))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


#### Making Tensors filled with ones

In [7]:
c = tf.ones_like(a)

with tf.Session() as sess:
    print(sess.run(c))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


#### Making Tensors filled with arbitrary value

In [9]:
d = tf.fill(dims=[3,3,3], value=0.5)

with tf.Session() as sess:
    print(sess.run(d))

[[[0.5 0.5 0.5]
  [0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]
  [0.5 0.5 0.5]]]


#### How to make a range of numbers

In [14]:
e = tf.lin_space(start=0., stop=25., num=3, name='by5')
f = tf.range(start=0., limit=25., delta=5., dtype=tf.float32, name='range')

with tf.Session() as sess:
    print('linspace', sess.run(e))
    print('range', sess.run(f))

linspace [ 0.  12.5 25. ]
range [ 0.  5. 10. 15. 20.]
