## Constants, Sequences, Variables, Ops

In [1]:
import tensorflow as tf

/Users/timlee/anaconda2/envs/py3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


## Constants
[https://www.tensorflow.org/api_docs/python/tf/constant](https://www.tensorflow.org/api_docs/python/tf/constant)

Constants are values that will never change through out your calculations. These stand fixed

In [2]:
# note that we are reshaping the matrix
a = tf.constant(value=[[1,2,3,4,5],[10,20,30,40,50]],
                dtype=tf.float32,
                shape=[5,2],
                name="tf_const",
                verify_shape=False
               )
a_reshape = tf.reshape(a, shape=[2,5])

with tf.Session() as sess:
    result = sess.run([a, a_reshape])
    print(result[0])
    print(result[1])

[[ 1.  2.]
 [ 3.  4.]
 [ 5. 10.]
 [20. 30.]
 [40. 50.]]
[[ 1.  2.  3.  4.  5.]
 [10. 20. 30. 40. 50.]]


#### Making Empty Tensors

In [3]:
b = tf.zeros_like(a)

with tf.Session() as sess:
    print(sess.run(b))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


#### Making Tensors filled with ones

In [4]:
c = tf.ones_like(a)

with tf.Session() as sess:
    print(sess.run(c))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


#### Making Tensors filled with arbitrary value

In [5]:
d = tf.fill(dims=[3,3,3], value=0.5)

with tf.Session() as sess:
    print(sess.run(d))

[[[0.5 0.5 0.5]
  [0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]
  [0.5 0.5 0.5]]]


#### How to make a range of numbers

In [6]:
e = tf.lin_space(start=0., stop=25., num=3, name='by5')
f = tf.range(start=0., limit=25., delta=5., dtype=tf.float32, name='range')

with tf.Session() as sess:
    print('linspace', sess.run(e))
    print('range', sess.run(f))

linspace [ 0.  12.5 25. ]
range [ 0.  5. 10. 15. 20.]


### Random Generators

In [7]:
tf.set_random_seed(1)
g = tf.random_normal(shape=(2,2))

with tf.Session() as sess:

    print('random normal', sess.run(g))

random normal [[-0.36537609  1.4068291 ]
 [-1.0580941  -0.66352683]]


## Key Operations

| Category | Examples| 
|---------- | --------|
|Element-wise mathematical Operations | Add, Sub, Mul, Div, Exp, Log, Greater, Less, Equal|
|Array operations | Concat, Slice, Split, Constant, Rank, Shape, Shuffle|
|Matrix Operations | MatMul, MatrixInverse, MatrixDeterminant,...|
|Stateful Operations | Variable, Assign, AssignAdd|
|NN Building Blocks | SoftMax, Sigmoid, ReLu, Convolution2D, MaxPool..|
|Checkpointing Operations | Save, Restore|
|Queue and synchronization operations | Enqueue, Dequeue, MutexAcquire, MutexRelease, ...|
|Control flow operations | Merge, Switch, Enter, Leave, NextIteration|

# Variables

> A TensorFlow variable is the best way to represent shared, persistent state manipulated by your program.
> Variables must be initialized, to serve as a best "guess", once initialized, these variables can be frozen, or changed throughout the graph calculation

> `tf.constant` is an op

> `tf.Variable` is a class with many op

Why use them? Constants are great, except that they are actually stored WITHIN the graph. The larger the graph, the more constants, and the larger the size of the graph. Use constants for primitive (and simple) types. Use variables and readers for data that will require more memory

### How to make variables Method 1: `tf.Variable`

In [8]:
scalar = tf.Variable(2, name='scalar')
matrix = tf.Variable([[0,1],[2,3]], name='mtx')
empty  = tf.Variable(tf.zeros([7, 3]), name='empty_mtx')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(scalar))
    print(sess.run(matrix))
    print(sess.run(empty))

2
[[0 1]
 [2 3]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### How to make variables Method 2: `tf.get_variable`

In [9]:
scalar = tf.get_variable("scalar1", initializer=tf.constant(2))
matrix = tf.get_variable("mtx1", initializer=tf.constant([[0,1],[2,3]]))
empty  = tf.get_variable('empty_mtx1', shape=(7,3), initializer=tf.zeros_initializer())

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(scalar))
    print(sess.run(matrix))
    print(sess.run(empty))

2
[[0 1]
 [2 3]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Variables: Initialization

Note that in the last two code blocks, the variables were **initialized**

The `global_variables_initializer()` initializes all variables in the graph
```
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    ...
```

For only a subset of variables:
```
with tf.Session() as sess:
    sess.run(tf.variables_initializer([var1, var2, var3]))
    ...
```

Or only 1 variable
```
with tf.Session() as sess:
    sess.run(W.initializer)
    ...
```




## Variables: `eval()`

In [17]:
weights = tf.Variable(tf.truncated_normal([5, 3]))
with tf.Session() as sess:
    sess.run(weights.initializer)
    print(weights.eval())

[[-0.70387346 -0.01866959  0.06857691]
 [ 0.5431961  -0.693588    1.159248  ]
 [-0.24034725  0.65011954  0.50049955]
 [-0.87781674 -0.95692325  1.9339348 ]
 [ 0.09642299  0.8811367   0.9550244 ]]


## Variables: `assign()`

In [25]:
ct1 = tf.Variable(10)
updated_ct1 = ct1.assign(1000)

with tf.Session() as sess:
    sess.run(ct1.initializer)
    sess.run(updated_ct1)
    print(ct1.eval())   

1000


### Trick Question: Whats `my var`?

In [26]:
my_var = tf.Variable(5)
double_my_var = my_var.assign(2*my_var)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    sess.run(double_my_var)
    print(my_var.eval())
    
    # run again
    sess.run(double_my_var)
    print(my_var.eval())
    
    # run again
    sess.run(double_my_var)
    print(my_var.eval())    

10
20
40


### Sessions & Variables

In [29]:
Z = tf.Variable(20)

sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(Z.initializer)
sess2.run(Z.initializer)

print(sess1.run(Z.assign_add(5)))
print(sess2.run(Z.assign_sub(3)))

print(sess1.run(Z.assign_add(5)))
print(sess2.run(Z.assign_sub(3)))

sess1.close()
sess2.close()


25
17
30
14


### Control Evaluation / Dependencies

In [36]:
# a = tf.Variable(2)
# b = tf.Variable(20)
# c = tf.Variable(200)
# add_c = c.assign_add(a)

# g = tf.Graph()
# with g.control_dependencies([add_c]):
#     add_d = a.assign_add(d)
    
# with tf.Session(graph=g) as sess:
#     sess.run(tf.global_variables_initializer)
#     sess.run(add_d)