## Placeholder

Tensorflow has 2 phases:

1. Assemble / build a graph
2. Use a session to execute operations in the graph

This can be counter-intuitive in math. How can `c = x + y` if `x` and `y` are not previously known? The best analogy is building pipes before any water is actually pumped through the system. As a result in this analogy `x` and `y` are pipe openings that data will be fed through

### Placeholder definition

> Inserts a placeholder for a tensor that will be always fed.

```
tf.placeholder
tf.placeholder_with_default
tf.sparse_placeholder
```
                   
And once you have a placeholder, you will need to feed data to the pipe, and this is done with **feed_dict**. Note, `shape=None` will take any sized input, but makes graph difficult to troubleshoot. Also, **placeholders are valid ops**

In [9]:
import tensorflow as tf

In [10]:
a = tf.placeholder(dtype=tf.float32,
                   shape=[2,3],
                   name='place_holder_1')

b = tf.constant([[1.,2.,3.],[4.,5.,6.]])

c = tf.add(a, b)

with tf.Session() as sess:
    # print(sess.run(c)) will give an error
    print()
    print(sess.run(c, feed_dict={a : [[0.,0.,1.],[1.,1.,1.]]}))


[[1. 2. 4.]
 [5. 6. 7.]]


### How do you feed multiple datapoints?

In [20]:
import numpy as np
a = tf.constant([1,2,3,4,5,6])
b = tf.placeholder(dtype=tf.int32, shape=None)
c = b + a
np_array = np.array([10,20])

with tf.Session() as sess:
    for val in np_array:
        print(sess.run(c, feed_dict={b:val}))

[11 12 13 14 15 16]
[21 22 23 24 25 26]


### Useful for Trouble Shooting

In [23]:
# hard to track the graph
a = tf.add(2,5)
b = tf.multiply(a,3)

with tf.Session() as sess:
    print(sess.run(b, feed_dict={a:15}))

45
